name: Plan infra
on:
  pull_request:
    branches:
    - prod
    - dev
env:
  AWS_REGION: ap-northeast-2
  TERRAFORM_VERSION: 1.12.2
  TERRAGRUNT_VERSION: 0.83.2
jobs:
  plan-infra:
    name: Plan infra
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        terraform_wrapper: false
    - name: Install Terragrunt
      run: |
        curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/terragrunt_linux_amd64 -o terragrunt
        chmod +x terragrunt
        sudo mv terragrunt /usr/local/bin/terragrunt
    - name: Initialize infra
      run: |
        cd env/${{ github.base_ref }} 
        terragrunt init --backend-bootstrap
    - name: Plan infra
      run: |
        cd env/${{ github.base_ref }} 
        terragrunt plan --all
